### PR TITLE
added youtube link to setup app

### PR DESCRIPTION
**Pull request by cinta-hash**

### CODE REVIEW

**Review by JudahSan — APPROVED** [review]
🤓 Thanks for the contribution!

**Comment by banta** [comment]
Thanks @cinta-hash, for that video and for your pull request. It'll really help many! Please share it on the WhatsApp group.

**Comment by cinta-hash** [comment]
> 🤓 Thanks for the contribution!

happy to contribute

**Comment by cinta-hash** [comment]
> Thanks @cinta-hash, for that video and for your pull request. It'll really help many! Please share it on the WhatsApp group.
happy to contribute. will do so

**Pull request merged**
